---
- name: Provision AWS
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    region: eu-west-1
    instance_type: t2.micro
    keypair: "saleemaws"
    ssh_location: 1.2.3.4/32
    stack_name: webapp-dev-stack-2
  tasks:
    - name: Create cfn stack
      cloudformation:
        stack_name: "{{ stack_name }}"
        region: "{{ region }}"
        disable_rollback: true
        state: present
        template: "cfn2.yaml"
        template_parameters:
          KeyName: "{{ keypair }}"
          InstanceType: "{{ instance_type }}"
          SSHLocation: "{{ ssh_location }}"
        tags:
          stack: "{{ stack_name }}"